### ISSUE TITLE
Cannot focus on nested modal if the underlying modal has modal:true

### ISSUE THREAD

**Issue by jackysee** [briceburg/jqModal#10]
If there are two modals to be opened, with the first one has `modal:true`, the input on the second modal cannot be focused. The plunker demonstrated the problem: http://plnkr.co/edit/ojo2xspL1oMnauSzKeCu?p=preview

**Comment by briceburg** [comment]
@jackysee ack -- I fear this behaviour is a causality of the rewrite. Are you able to work around this issue by passing modal: true to the second modal? E.g. http://plnkr.co/edit/rzRgCD0fgPWRR3YWx2EE?p=preview

**Comment by jackysee** [comment]
Actually I'm using an much older version with the same problem. I'm seeking to see if the latest version can have this fix. The requirement is that the second modal can be discarded by clicking outside.

**Comment by briceburg** [comment]
Got it. One way would be to override the $.jqm.focusFunc  . Give the second modal's overlay a special class, be sure the z-index of the second modal is greater than the overlays, and examine the event target (e) of $.jqm.focusFunc, if it is the second modal, return true. if it is the second modal's overlay, close the second modal.

**Comment by jackysee** [comment]
I happened to patch fix the old version such that it will allow key/mouse events on higher layer. Don't know if this can apply to the rewrite version. 
http://plnkr.co/edit/X2j1wKNnxTITHNrgdUO0?p=preview

**Comment by jackysee** [comment]
Try to apply the logic to the rewrite version. Demonstrated here: http://plnkr.co/edit/93nfFuMG781Y0vVIf5UF?p=preview

Created a pull request:  https://github.com/briceburg/jqModal/pull/11

**Comment by briceburg** [comment]
@jackysee This was actually a very simple z-index issue. See:

http://plnkr.co/edit/dZ3dzir9QLNhUmgYEF7p?p=preview

I've also updated jqModal to 1.2.0 and pass the event along to the focus func, so things are fancy and flexible. For instance, see:

http://plnkr.co/edit/xsQX4v2Bo3Uqb6QML5Mh?p=preview

This should allow you to do *anything* you want.  

Hope this helps!
