### ISSUE TITLE
Close modal AJAX doesn't work

### ISSUE THREAD

**Issue by GhosToM31** [briceburg/jqModal#24]
Hi, 

I'm using the jQuery version (v.2.1.4) and the last jqModal version (+r25) on a website. Everything works fine except to close a modal when I'm calling it with trigger. I was thinking about a conflict problem but it seems there is the same problem on the demo website : trying the example n°2 (AJAX) it's impossible to close the modal by clicking on the differents links...

**Comment by pascalBokBok** [comment]
@briceburg I confirm this issue. I'm experiencing the same issue on the website example 2 Ajax.
I'm using Chrome Version 48.0.2564.97 (64-bit)

**Comment by pascalBokBok** [comment]
It doesn't work in firefox either.

**Comment by pascalBokBok** [comment]
I'm using v 1.2.1 as a work around. 1.3 has the same problem as 1.4

**Comment by briceburg** [comment]
I'll see what I can find out ASAP -- apologies re: the radio delay!

**Comment by turnround** [comment]
I can also confirm this issue, and have reverted back to v1.2.1 as the only solution in the meantime.
