### ISSUE TITLE
no images / css for examples - http://jquery.iceburg.net/jqModal/#examples

### ISSUE THREAD

**Issue by mhenke** [briceburg/jqModal#7]
Hi,

I am trying the examples locally but I don't see any links for images. Could you please package everything together (css, images, and js) and provide for download?

http://jquery.iceburg.net/jqModal/#examples

Thanks

**Comment by briceburg** [comment]
@mhenke the entire usage/example site is due a rewrite. For now, I would rely on the README.md example, the examples dir, and browsing the https://github.com/iceburg-net/jquery.iceburg.net/tree/master/www-1/jqModal  site (where examples and images may be downloaded).
