### ISSUE TITLE
to top does not properly append to body in ie8.

### ISSUE THREAD

**Issue by travisdmathis** [briceburg/jqModal#8]
to top is not appending to the body as it should in ie8.  works fine in ie9+..  is this intended bryce?  do you still support ie8 with jqmodal?

    div.jqm({
        toTop: true,
        modal: true,
        overlay: 100,
    }).jqmShow();

**Comment by briceburg** [comment]
IE8 is definitely supported. I dropped ActiveX bleed-through code for IE6 during the rewrite, so that browser is not 100%, but IE8 should be. Can you pass along your code example (@ http://plnkr.co/ ) ?
